stages:
    - test
    - lint

.cargo_test_template: &cargo_test
    stage: test

    variables:
        RUST_BACKTRACE: "FULL"

    before_script:
        - mkdir -p .cargo_cache
        # Only stuff inside the repo directory can be cached
        # Override the CARGO_HOME variable to force it location
        - export CARGO_HOME="${PWD}/.cargo_cache"
    script:
        - rustc -Vv && cargo -Vv
        - cargo build
        - cargo test
        # - cargo test -- --ignored

    cache:
        # JOB_NAME - Each job will have it's own cache
        key: "$CI_JOB_NAME"
        paths:
            - target/
            - .cargo_cache/

# stable:test:
#     # https://hub.docker.com/_/rust/
#     image: "rust"
#     <<: *cargo_test

nightly:test:
    # https://hub.docker.com/r/rustlang/rust/
    image: "rustlang/rust:nightly"
    <<: *cargo_test

# Configure and run rustfmt on nightly
# Exits and builds fails if on bad format
rustfmt:
    image: "registry.gitlab.com/alatiera/rustfmt-oci-image/rustfmt:nightly"
    stage: lint
    script:
        - rustc -Vv && cargo -Vv
        - cargo fmt --version
        - cargo fmt --all -- --write-mode=diff
